// Библиотека тем для выпусков.
//
// Каждая пара подобрана ВНУТРИ одной категории: фастфуд против фастфуда,
// торт против торта. Иначе выбор нечестный и голосовать неинтересно.
//
// Формат пары: [верх, страна, низ, страна, процент верха]
// Пустая строка вместо страны — плашка просто не показывается.
//
// Названия намеренно простые и «снимаемые»: у Pexels на каждый запрос
// примерно два клипа, и чем обычнее слово, тем выше шанс на хороший кадр.

export const THEMES = [
  {
    id: "desserts",
    shot: "close",
    edition: "DESSERTS EDITION",
    hook: "WHAT WOULD YOU EAT FOR FREE?",
    outro: {
      title: "SWEET TOOTH?",
      subtitle: "comment your pick",
      cta: "more quizzes on my profile",
    },
    pairs: [
      ["Tiramisu", "", "Brownie", "", 45],
      ["Croissant", "", "Cinnamon Roll", "", 42],
      ["Macarons", "", "Cupcakes", "", 44],
      ["Apple Pie", "", "Chocolate Mousse", "", 43],
      ["Gelato", "", "Frozen Yogurt", "", 68],
      ["Churros", "", "Waffles", "", 46],
      ["Strawberry Cake", "", "Carrot Cake", "", 64],
      ["Pudding", "", "Panna Cotta", "", 45],
      ["Chocolate Fondue", "", "Caramel Popcorn", "", 62],
    ],
  },
  {
    id: "breakfast",
    shot: "close",
    edition: "BREAKFAST EDITION",
    hook: "WHAT WOULD YOU EAT FOR FREE?",
    outro: {
      title: "BREAKFAST OF CHAMPIONS?",
      subtitle: "tell me below",
      cta: "follow for daily quizzes",
    },
    pairs: [
      ["Pancakes", "", "French Toast", "", 58],
      ["Omelette", "", "Scrambled Eggs", "", 45],
      ["Bacon", "", "Sausages", "", 68],
      ["Avocado Toast", "", "Bagel", "", 44],
      ["Granola", "", "Oatmeal", "", 61],
      ["Fresh Orange Juice", "", "Smoothie", "", 46],
      ["Espresso", "", "Green Tea", "", 66],
      ["Croissant", "", "Muffin", "", 57],
      ["Fruit Salad", "", "Yogurt Bowl", "", 51],
    ],
  },
  {
    id: "street-food",
    shot: "close",
    edition: "STREET FOOD EDITION",
    hook: "WHAT WOULD YOU EAT FOR FREE?",
    outro: {
      title: "WHERE WOULD YOU EAT?",
      subtitle: "comment your country",
      cta: "more food quizzes here",
    },
    pairs: [
      ["Kebab", "Turkey", "Hot Dog", "Germany", 52],
      ["Falafel", "Egypt", "Dumplings", "China", 38],
      ["Shawarma", "Lebanon", "Burrito", "Mexico", 44],
      ["Spring Rolls", "Vietnam", "Samosa", "India", 57],
      ["Crepes", "France", "Popcorn", "USA", 60],
      ["Pizza Slice", "Italy", "Chips", "England", 43],
      ["Poutine", "Canada", "Loaded Fries", "Belgium", 41],
      ["Gyros", "Greece", "Empanadas", "Argentina", 55],
      ["Grilled Corn", "Mexico", "Roasted Chestnuts", "Italy", 67],
    ],
  },
  {
    id: "drinks",
    shot: "close",
    edition: "DRINKS EDITION",
    hook: "WHAT WOULD YOU DRINK FOR FREE?",
    outro: {
      title: "WHAT'S IN YOUR CUP?",
      subtitle: "tell me in the comments",
      cta: "more quizzes on my profile",
    },
    pairs: [
      ["Latte", "", "Milkshake", "", 54],
      ["Lemonade", "", "Iced Tea", "", 48],
      ["Hot Chocolate", "", "Cappuccino", "", 55],
      ["Bubble Tea", "", "Smoothie", "", 58],
      ["Coconut Water", "", "Watermelon Juice", "", 42],
      ["Espresso", "", "Matcha", "", 56],
      ["Mango Juice", "", "Strawberry Shake", "", 45],
      ["Herbal Tea", "", "Fresh Mint Tea", "", 40],
      ["Cold Brew", "", "Iced Latte", "", 46],
    ],
  },
  {
    id: "snacks",
    shot: "close",
    edition: "SNACKS EDITION",
    hook: "WHAT WOULD YOU EAT FOR FREE?",
    outro: {
      title: "MIDNIGHT SNACK?",
      subtitle: "comment your go-to",
      cta: "follow for more",
    },
    pairs: [
      ["Popcorn", "", "Pretzel", "", 65],
      ["Potato Chips", "", "Nachos", "", 52],
      ["Cookies", "", "Brownies", "", 53],
      ["Peanuts", "", "Almonds", "", 45],
      ["Chocolate Bar", "", "Gummy Bears", "", 63],
      ["Cheese Board", "", "Olives", "", 71],
      ["Onion Rings", "", "Mozzarella Sticks", "", 44],
      ["Ice Cream Cone", "", "Donut", "", 55],
      ["Dark Chocolate", "", "Milk Chocolate", "", 41],
    ],
  },
  {
    id: "asian-food",
    shot: "close",
    edition: "ASIAN FOOD EDITION",
    hook: "WHAT WOULD YOU EAT FOR FREE?",
    outro: {
      title: "HOW MANY MATCHED?",
      subtitle: "comment your favourite",
      cta: "more food quizzes here",
    },
    pairs: [
      ["Sushi", "Japan", "Dumplings", "China", 58],
      ["Ramen", "Japan", "Pho", "Vietnam", 62],
      ["Pad Thai", "Thailand", "Fried Rice", "China", 55],
      ["Curry", "India", "Teriyaki Chicken", "Japan", 57],
      ["Fried Chicken", "Korea", "Miso Soup", "Japan", 47],
      ["Dim Sum", "China", "Gyoza", "Japan", 46],
      ["Noodles", "China", "Udon", "Japan", 54],
      ["Sashimi", "Japan", "Korean BBQ", "Korea", 38],
      ["Mango Sticky Rice", "Thailand", "Mochi", "Japan", 45],
    ],
  },
  {
    id: "bbq",
    shot: "close",
    edition: "BBQ EDITION",
    hook: "WHAT WOULD YOU EAT FOR FREE?",
    outro: {
      title: "HUNGRY YET?",
      subtitle: "tell me what you picked",
      cta: "follow for more",
    },
    pairs: [
      ["Steak", "", "Ribs", "", 57],
      ["Grilled Chicken", "", "Grilled Fish", "", 63],
      ["Burger", "", "Sausage", "", 66],
      ["Kebab", "", "Grilled Shrimp", "", 48],
      ["Pulled Pork", "", "Brisket", "", 46],
      ["Grilled Corn", "", "Grilled Vegetables", "", 62],
      ["Lamb Chops", "", "Pork Belly", "", 47],
      ["Barbecue Wings", "", "Grilled Salmon", "", 58],
      ["Hot Dog", "", "Grilled Cheese", "", 45],
    ],
  },
  {
    id: "fruits",
    shot: "close",
    edition: "FRUITS EDITION",
    hook: "WHAT WOULD YOU EAT FOR FREE?",
    outro: {
      title: "DID WE AGREE?",
      subtitle: "comment your favourite",
      cta: "more quizzes on my profile",
    },
    pairs: [
      ["Strawberry", "", "Raspberry", "", 68],
      ["Mango", "", "Pineapple", "", 61],
      ["Watermelon", "", "Melon", "", 72],
      ["Kiwi", "", "Pear", "", 70],
      ["Grapes", "", "Cherries", "", 52],
      ["Banana", "", "Avocado", "", 56],
      ["Orange", "", "Lemon", "", 79],
      ["Blueberry", "", "Blackberry", "", 58],
      ["Coconut", "", "Papaya", "", 64],
    ],
  },
  {
    id: "dream-cities",
    shot: "wide",
    edition: "DREAM CITIES EDITION",
    hook: "IF IT WAS FREE, WHERE WOULD YOU GO?",
    outro: {
      title: "WHERE ARE YOU GOING?",
      subtitle: "comment your dream city",
      cta: "more travel quizzes here",
    },
    pairs: [
      ["Paris", "France", "New York", "USA", 48],
      ["Tokyo", "Japan", "Dubai", "UAE", 62],
      ["London", "England", "Rome", "Italy", 47],
      ["Barcelona", "Spain", "Amsterdam", "Netherlands", 56],
      ["Istanbul", "Turkey", "Prague", "Czechia", 45],
      ["Singapore", "Singapore", "Hong Kong", "China", 58],
      ["Venice", "Italy", "Vienna", "Austria", 65],
      ["Seoul", "Korea", "Bangkok", "Thailand", 57],
      ["Lisbon", "Portugal", "Copenhagen", "Denmark", 55],
    ],
  },
  {
    id: "beaches",
    shot: "wide",
    edition: "BEACHES EDITION",
    hook: "IF IT WAS FREE, WHERE WOULD YOU GO?",
    outro: {
      title: "PACK YOUR BAGS",
      subtitle: "comment your beach",
      cta: "follow for more travel",
    },
    pairs: [
      ["Maldives", "Maldives", "Mauritius", "Mauritius", 58],
      ["Hawaii", "USA", "Seychelles", "Seychelles", 60],
      ["Santorini", "Greece", "Amalfi Coast", "Italy", 57],
      ["Phuket", "Thailand", "Zanzibar", "Tanzania", 61],
      ["Cancun", "Mexico", "Barbados", "Barbados", 55],
      ["Fiji", "Fiji", "Tahiti", "France", 52],
      ["Ibiza", "Spain", "Mykonos", "Greece", 56],
      ["Copacabana", "Brazil", "Miami Beach", "USA", 44],
      ["Sardinia", "Italy", "Algarve", "Portugal", 58],
    ],
  },
  {
    id: "islands",
    shot: "wide",
    edition: "ISLANDS EDITION",
    hook: "IF IT WAS FREE, WHERE WOULD YOU GO?",
    outro: {
      title: "WHICH ISLAND WON?",
      subtitle: "tell me in the comments",
      cta: "more quizzes on my profile",
    },
    pairs: [
      ["Bora Bora", "Pacific", "Maldives", "Indian Ocean", 47],
      ["Iceland", "Atlantic", "Greenland", "Arctic", 74],
      ["Sicily", "Mediterranean", "Crete", "Mediterranean", 54],
      ["Madeira", "Atlantic", "Canary Islands", "Atlantic", 44],
      ["Bali", "Indian Ocean", "Sri Lanka", "Indian Ocean", 68],
      ["Cyprus", "Mediterranean", "Malta", "Mediterranean", 55],
      ["Jamaica", "Caribbean", "Cuba", "Caribbean", 52],
      ["Corsica", "Mediterranean", "Mallorca", "Mediterranean", 45],
      ["Galapagos", "Pacific", "Azores", "Atlantic", 60],
    ],
  },
  {
    id: "wonders-of-nature",
    shot: "wide",
    edition: "WONDERS OF NATURE EDITION",
    hook: "WHICH WONDER WOULD YOU SEE FIRST?",
    outro: {
      title: "SEEN ANY OF THESE?",
      subtitle: "comment which one",
      cta: "follow for more",
    },
    pairs: [
      ["Northern Lights", "Norway", "Milky Way", "Chile", 63],
      ["Grand Canyon", "USA", "Niagara Falls", "Canada", 53],
      ["Sahara Desert", "Morocco", "Amazon Rainforest", "Brazil", 46],
      ["Glacier", "Iceland", "Volcano", "Indonesia", 44],
      ["Coral Reef", "Australia", "Blue Lagoon", "Iceland", 55],
      ["Redwood Forest", "USA", "Bamboo Forest", "Japan", 47],
      ["Salt Flats", "Bolivia", "Sand Dunes", "Namibia", 54],
      ["Ice Cave", "Iceland", "Waterfall", "Norway", 52],
      ["Cherry Blossom", "Japan", "Lavender Fields", "France", 61],
    ],
  },
  {
    id: "night-cities",
    shot: "wide",
    edition: "NIGHT CITIES EDITION",
    hook: "48 HOURS, ONE CITY. WHICH ONE?",
    outro: {
      title: "BEST CITY AT NIGHT?",
      subtitle: "comment your pick",
      cta: "more travel quizzes here",
    },
    pairs: [
      ["Tokyo at Night", "Japan", "New York at Night", "USA", 57],
      ["Dubai Skyline", "UAE", "Shanghai Skyline", "China", 61],
      ["Paris at Night", "France", "London at Night", "England", 62],
      ["Las Vegas", "USA", "Macau", "China", 71],
      ["Hong Kong Skyline", "China", "Singapore Skyline", "Singapore", 46],
      ["Times Square", "USA", "Piccadilly Circus", "England", 66],
      ["Seoul at Night", "Korea", "Bangkok at Night", "Thailand", 55],
      ["Moscow at Night", "Russia", "Istanbul at Night", "Turkey", 44],
      ["Sydney Harbour", "Australia", "Rio de Janeiro", "Brazil", 52],
    ],
  },
  {
    id: "mountains",
    shot: "wide",
    edition: "MOUNTAINS EDITION",
    hook: "YOU HAVE 3 DAYS. WHICH MOUNTAIN?",
    outro: {
      title: "HOW HIGH WOULD YOU GO?",
      subtitle: "tell me below",
      cta: "follow for more travel",
    },
    pairs: [
      ["Swiss Alps", "Switzerland", "Rocky Mountains", "USA", 62],
      ["Mount Fuji", "Japan", "Matterhorn", "Switzerland", 58],
      ["Dolomites", "Italy", "Norwegian Fjords", "Norway", 47],
      ["Himalayas", "Nepal", "Andes", "Peru", 61],
      ["Banff", "Canada", "Patagonia", "Chile", 48],
      ["Mount Everest", "Nepal", "Kilimanjaro", "Tanzania", 72],
      ["Yosemite", "USA", "Torres del Paine", "Chile", 63],
      ["Pyrenees", "Spain", "Carpathians", "Romania", 56],
      ["Iceland Highlands", "Iceland", "Scottish Highlands", "Scotland", 55],
    ],
  },
  {
    id: "lakes-waterfalls",
    shot: "wide",
    edition: "LAKES AND WATERFALLS EDITION",
    hook: "WHERE ARE YOU SWIMMING TODAY?",
    outro: {
      title: "HOW MANY MATCHED?",
      subtitle: "comment your favourite",
      cta: "more quizzes on my profile",
    },
    pairs: [
      ["Niagara Falls", "Canada", "Iguazu Falls", "Argentina", 58],
      ["Lake Como", "Italy", "Lake Bled", "Slovenia", 55],
      ["Plitvice Lakes", "Croatia", "Banff Lakes", "Canada", 52],
      ["Victoria Falls", "Zambia", "Angel Falls", "Venezuela", 54],
      ["Lake Louise", "Canada", "Lake Tahoe", "USA", 46],
      ["Blue Lagoon", "Iceland", "Hot Springs", "Japan", 57],
      ["Amazon River", "Brazil", "Nile River", "Egypt", 55],
      ["Crater Lake", "USA", "Lake Baikal", "Russia", 45],
      ["Seljalandsfoss", "Iceland", "Gullfoss", "Iceland", 51],
    ],
  },
  {
    id: "summer-winter",
    shot: "wide",
    edition: "SUMMER OR WINTER EDITION",
    hook: "SUMMER OR WINTER? PICK ONE",
    outro: {
      title: "SO... SUMMER OR WINTER?",
      subtitle: "settle it in the comments",
      cta: "follow for more",
    },
    pairs: [
      ["Beach Day", "", "Ski Resort", "", 64],
      ["Ice Cream", "", "Hot Chocolate", "", 52],
      ["Swimming Pool", "", "Cozy Fireplace", "", 54],
      ["Sunglasses", "", "Snowboard", "", 45],
      ["Summer Festival", "", "Christmas Market", "", 47],
      ["Surfing", "", "Snowboarding", "", 55],
      ["Tropical Island", "", "Snowy Cabin", "", 62],
      ["Barbecue", "", "Winter Soup", "", 63],
      ["Sunset Beach", "", "Northern Lights", "", 44],
    ],
  },
  {
    id: "luxury",
    shot: "wide",
    edition: "LUXURY EDITION",
    hook: "YOU HAVE $1,000,000. WHAT DO YOU BUY?",
    outro: {
      title: "WHAT DID YOU TAKE?",
      subtitle: "comment your choice",
      cta: "more quizzes on my profile",
    },
    pairs: [
      ["Private Jet", "", "Luxury Yacht", "", 46],
      ["Penthouse", "", "Beach Villa", "", 44],
      ["Helicopter", "", "Sports Car", "", 35],
      ["Luxury Watch", "", "Diamond Ring", "", 55],
      ["First Class Flight", "", "Presidential Suite", "", 47],
      ["Private Island", "", "Mountain Chalet", "", 68],
      ["Designer Bag", "", "Designer Shoes", "", 61],
      ["Infinity Pool", "", "Rooftop Terrace", "", 58],
      ["Vintage Car", "", "Luxury Motorcycle", "", 57],
    ],
  },
  {
    id: "supercars",
    shot: "wide",
    edition: "SUPERCARS EDITION",
    hook: "THE KEYS ARE YOURS. WHICH CAR?",
    outro: {
      title: "WHAT ARE YOU DRIVING?",
      subtitle: "comment your dream car",
      cta: "follow for more",
    },
    pairs: [
      ["Ferrari", "Italy", "Lamborghini", "Italy", 47],
      ["Porsche", "Germany", "Aston Martin", "England", 60],
      ["Bugatti", "France", "McLaren", "England", 58],
      ["Mustang", "USA", "Corvette", "USA", 56],
      ["Rolls Royce", "England", "Bentley", "England", 58],
      ["Mercedes", "Germany", "BMW", "Germany", 51],
      ["Jeep", "USA", "Land Rover", "England", 46],
      ["Tesla", "USA", "Audi", "Germany", 55],
      ["Maserati", "Italy", "Jaguar", "England", 45],
    ],
  },
  {
    id: "dream-homes",
    shot: "wide",
    edition: "DREAM HOMES EDITION",
    hook: "YOU MOVE IN TOMORROW. WHICH HOME?",
    outro: {
      title: "WHERE WOULD YOU LIVE?",
      subtitle: "tell me in the comments",
      cta: "more quizzes on my profile",
    },
    pairs: [
      ["Beach House", "", "Mountain Cabin", "", 58],
      ["City Penthouse", "", "Countryside Villa", "", 46],
      ["Modern House", "", "Historic Mansion", "", 54],
      ["Treehouse", "", "Houseboat", "", 55],
      ["Loft Apartment", "", "Cottage", "", 53],
      ["Desert House", "", "Forest Cabin", "", 38],
      ["Lake House", "", "Island Bungalow", "", 47],
      ["Glass House", "", "Stone Castle", "", 43],
      ["Tiny House", "", "Luxury Villa", "", 26],
    ],
  },
  {
    id: "gadgets",
    shot: "close",
    edition: "GADGETS EDITION",
    hook: "YOU HAVE $2,000. WHAT DO YOU TAKE?",
    outro: {
      title: "HOW MANY MATCHED?",
      subtitle: "comment your pick",
      cta: "follow for more",
    },
    pairs: [
      ["Laptop", "", "Tablet", "", 71],
      ["Smartphone", "", "Smartwatch", "", 76],
      ["Camera", "", "Drone", "", 54],
      ["Headphones", "", "Speaker", "", 63],
      ["Gaming Console", "", "Gaming PC", "", 48],
      ["Electric Scooter", "", "Electric Bike", "", 43],
      ["VR Headset", "", "Home Cinema", "", 42],
      ["Vinyl Player", "", "Guitar", "", 45],
      ["Espresso Machine", "", "Air Fryer", "", 47],
    ],
  },
  {
    id: "animals",
    shot: "wide",
    edition: "ANIMALS EDITION",
    hook: "PICK WHO YOU MEET OUTSIDE YOUR HOUSE. NO REFUSING",
    outro: {
      title: "WHICH ONE WON?",
      subtitle: "comment your favourite",
      cta: "more quizzes on my profile",
    },
    pairs: [
      ["Lion", "", "Tiger", "", 48],
      ["Elephant", "", "Giraffe", "", 58],
      ["Panda", "", "Koala", "", 62],
      ["Wolf", "", "Fox", "", 55],
      ["Eagle", "", "Falcon", "", 61],
      ["Horse", "", "Deer", "", 64],
      ["Bear", "", "Gorilla", "", 52],
      ["Zebra", "", "Cheetah", "", 38],
      ["Owl", "", "Peacock", "", 57],
    ],
  },
  {
    id: "pets",
    shot: "wide",
    edition: "PETS EDITION",
    hook: "WHICH ONE COMES HOME WITH YOU?",
    outro: {
      title: "TEAM DOG OR TEAM CAT?",
      subtitle: "settle it in the comments",
      cta: "follow for more",
    },
    pairs: [
      ["Dog", "", "Cat", "", 53],
      ["Puppy", "", "Kitten", "", 48],
      ["Golden Retriever", "", "Husky", "", 54],
      ["Rabbit", "", "Hamster", "", 58],
      ["Parrot", "", "Canary", "", 72],
      ["Goldfish", "", "Turtle", "", 41],
      ["Pony", "", "Goat", "", 66],
      ["Corgi", "", "Bulldog", "", 60],
      ["Guinea Pig", "", "Ferret", "", 55],
    ],
  },
  {
    id: "sea-creatures",
    shot: "wide",
    edition: "SEA CREATURES EDITION",
    hook: "WHO WOULD YOU SWIM WITH IF THEY COULDN'T SEE YOU?",
    outro: {
      title: "WOULD YOU DIVE IN?",
      subtitle: "tell me below",
      cta: "more quizzes on my profile",
    },
    pairs: [
      ["Dolphin", "", "Whale", "", 57],
      ["Sea Turtle", "", "Manta Ray", "", 62],
      ["Shark", "", "Octopus", "", 53],
      ["Jellyfish", "", "Seahorse", "", 45],
      ["Coral Reef", "", "Kelp Forest", "", 68],
      ["Penguin", "", "Seal", "", 63],
      ["Clownfish", "", "Angelfish", "", 66],
      ["Starfish", "", "Crab", "", 56],
      ["Orca", "", "Sea Lion", "", 58],
    ],
  },
  {
    id: "birds",
    shot: "wide",
    edition: "BIRDS EDITION",
    hook: "WHO WOULD YOU PUT ON YOUR HAND? NO REFUSING",
    outro: {
      title: "WHICH ONE WOULD YOU KEEP?",
      subtitle: "comment your favourite",
      cta: "follow for more",
    },
    pairs: [
      ["Eagle", "", "Owl", "", 47],
      ["Peacock", "", "Flamingo", "", 54],
      ["Parrot", "", "Toucan", "", 58],
      ["Swan", "", "Crane", "", 65],
      ["Hummingbird", "", "Kingfisher", "", 57],
      ["Penguin", "", "Puffin", "", 68],
      ["Falcon", "", "Hawk", "", 53],
      ["Pelican", "", "Heron", "", 52],
      ["Seagull", "", "Dove", "", 45],
    ],
  },
  {
    id: "flowers",
    shot: "close",
    edition: "FLOWERS EDITION",
    hook: "WHICH FLOWERS ARE YOU GIVING YOUR MOM?",
    outro: {
      title: "WHAT DID YOU PICK?",
      subtitle: "comment your flower",
      cta: "more quizzes on my profile",
    },
    pairs: [
      ["Roses", "", "Tulips", "", 61],
      ["Sunflowers", "", "Daisies", "", 58],
      ["Orchid", "", "Lily", "", 55],
      ["Lavender", "", "Jasmine", "", 57],
      ["Cherry Blossom", "", "Magnolia", "", 66],
      ["Peony", "", "Hydrangea", "", 60],
      ["Poppy Field", "", "Lavender Field", "", 42],
      ["Wildflowers", "", "Garden Roses", "", 52],
      ["Cactus Flower", "", "Water Lily", "", 44],
    ],
  },
];

export const themeById = (id) => THEMES.find((t) => t.id === id);

// Пары → раунды в том виде, в каком их ждёт ролик.
export const roundsOf = (theme, palette) => {
  const T = palette?.top ?? "#C1613C";
  const Q = palette?.bottom ?? "#12888A";
  const slug = (s) =>
    s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

  return theme.pairs.map(([top, topCountry, bottom, bottomCountry, topPercent]) => ({
    top: { label: top, image: `${slug(top)}.jpg`, color: T, country: topCountry },
    bottom: {
      label: bottom,
      image: `${slug(bottom)}.jpg`,
      color: Q,
      country: bottomCountry,
    },
    topPercent,
  }));
};
